name: matrix
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetArch: ["x86", "x64", "arm"]
        flavor: ["debug", "retail"]
    # name: static name
    name: Compile ${{ matrix.targetArch }}
    steps:
    - name: Compile
      run: echo imaginaryCompiler -A ${{ matrix.targetArch }} -F ${{ matrix.flavor }}
      
